name: First Workflow
on: 
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Running testing step"
      - name: testing-code
        run: |
          echo "Testing code"
          pwd
          ls -ltr
