name: First Workflow
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Running testing step"
      - name: testing-code
        run: |
          echo "Testing code"
          pwd
          ls -ltra
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: testing again
        run: echo "Hello World!!"
      - name: test code again
        run: |
          echo "Bye bye..!!!"
          echo "See you soon..........!!!!!!!!!!!"
